services:
  backend-product:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-product
    restart: always
    depends_on:
      db-mysql:
        condition: service_healthy
      cache-radis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"

networks:
  network-orca-studio:
    external: true
