spring:
  application:
    name: orca-studio

  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${CACHE_HOST}
      port: ${CACHE_PORT}

  elasticsearch:
    uris: ${ELASTICSEARCH_URI}

